host: 127.0.0.1:8080/v1
info:
  contact: {}
  description: project stats for all project from links123.com
  license: {}
  title: project stats for all project from links123.com
  version: "1.0"
paths: {}
swagger: "2.0"
