settings:
  legacy:
    force: false
    interval: 100s
server:
  status: true
  open: false
  port: 3000
  host: localhost
schema:
  - name: tcp-server
    path: .
    commands:
      run:
        status: true
        args:
          - -i
    args:
      - tcp
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - vendor
