// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-06-11 01:31:19.492495763 +0800 CST m=+0.184470647

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "project stats for all project from links123.com",
        "title": "project stats for all project from links123.com",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "127.0.0.1:8080/v1",
    "paths": {}
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
